[traefik-auth]
enabled  = true
filter   = traefik-auth
backend  = systemd
journalmatch = _SYSTEMD_UNIT=docker.service CONTAINER_NAME=traefik
maxretry = 10
findtime = 5m
bantime  = 1h
action   = ufw[application=Traefik,blocktype=DROP]
